import pandas as pd
from pathlib import Path

def merge_databases():
    # --- 1. SET UP PATHS ---
    # Based on your previous context, we build the path dynamically
    root_dir = r"C:\Users\perla\Documents\AT\TeamProject\GitHub\TeamProject"
    target_folder = Path(root_dir) / "scripts" / "approach_grf_markers"
    
    if not target_folder.exists():
        print(f"[Error] Target folder not found: {target_folder}")
        return

    # Define the 4 cases and the exact suffixes generated by your V2 export
    cases = {
        "Case1": "Case1_Markers_GRF.csv",
        "Case2": "Case2_IK.csv",
        "Case3": "Case3_ID.csv",
        "Case4": "Case4_IK_ID.csv"
    }
    
    # The 5 databases to look for
    databases = ["DB1", "DB2", "DB3", "DB4", "DB5"]
    
    print(f"\n--- Starting Database Merger in: {target_folder.name} ---")
    
    # --- 2. LOOP THROUGH EACH CASE ---
    for case_key, suffix in cases.items():
        print(f"\nProcessing {case_key} ({suffix})...")
        
        combined_data = []
        
        # --- 3. LOAD EACH DB FOR THE CURRENT CASE ---
        for db in databases:
            # Reconstruct the expected filename (e.g., "DB1_Case1_Markers_GRF.csv")
            file_name = f"{db}_{suffix}"
            file_path = target_folder / file_name
            
            if file_path.exists():
                print(f"  -> Loading {file_name}...")
                # Load the CSV into a pandas DataFrame
                df = pd.read_csv(file_path)
                combined_data.append(df)
            else:
                print(f"  [Warning] File not found: {file_name}")
        
        # --- 4. MERGE AND SAVE ---
        if combined_data:
            # Stack all the loaded dataframes on top of each other
            merged_df = pd.concat(combined_data, ignore_index=True)
            
            # Create the final output filename (e.g., "All_DBs_Case1_Markers_GRF.csv")
            output_name = f"All_DBs_{suffix}"
            output_path = target_folder / output_name
            
            # Save the massive matrix
            merged_df.to_csv(output_path, index=False)
            
            print(f"[Success] Merged {len(combined_data)} databases into {output_name}")
            print(f"          Final Matrix Shape: {merged_df.shape[0]} trials x {merged_df.shape[1]} features")
        else:
            print(f"[Failed] No files were found for {case_key}. Skipping merge.")

if __name__ == "__main__":
    merge_databases()