"""
Merge processed database outputs across Databses (E.g. DB1-DB5).

Usage:
    1. Update `root_dir` to the local project/repository path.
    2. Run:
           python join_dbfeatures.py

The script searches for the four exported case files from DB1-DB5,
combines the available databases for each case, and saves the merged
matrices  in separate case folders inside the `MLP/` folder.
"""

import pandas as pd
from pathlib import Path

def merge_databases():
    # Path to the root directory of the project.
    # Update this path when running the code on another computer.
    root_dir = r"C:\Users\perla\Documents\AT\TeamProject\GitHub\TeamProject\GitLab"
    input_folder = Path(root_dir) / "DATA"
    target_folder = Path(root_dir) / "MLP"
    
    if not input_folder.exists():
        print(f"[Error] Input folder not found: {input_folder}")
        return

    # Case files generated by export_database_results().
    # Each case is saved in its corresponding folder inside MLP/.
    cases = {
        "Case1": {
            "file": "Case1_Markers_GRF.csv",
            "folder": "case1"
        },
        "Case2": {
            "file": "Case2_IK.csv",
            "folder": "case2"
        },
        "Case3": {
            "file": "Case3_ID.csv",
            "folder": "case3"
        },
        "Case4": {
            "file": "Case4_IK_ID.csv",
            "folder": "case4"
        }
    }

    # Databases to merge.
    databases = ["DB1", "DB2", "DB3", "DB4", "DB5"]

    print(f"\n--- Starting Database Merger in: {target_folder.name} ---")

    # Loop through each case and combine the available databases.
    for case_key, case_info in cases.items():
        suffix = case_info["file"]
        case_folder = target_folder / case_info["folder"]

        # Create the case folder if it does not already exist.
        case_folder.mkdir(parents=True, exist_ok=True)

        print(f"\nProcessing {case_key} ({suffix})...")

        combined_data = []

        # Load the corresponding file from each database.
        for db in databases:
            # Reconstruct the expected filename
            # (e.g. "DB1_Case1_Markers_GRF.csv").
            file_name = f"{db}_{suffix}"
            file_path = input_folder / file_name

            if file_path.exists():
                print(f"  -> Loading {file_name}...")

                # Load the CSV into a pandas DataFrame.
                df = pd.read_csv(file_path)
                combined_data.append(df)
            else:
                print(f"  [Warning] File not found: {file_name}")

        # Merge and save the data for the current case.
        if combined_data:
            merged_df = pd.concat(combined_data, ignore_index=True)

            output_name = f"All_DBs_{suffix}"
            output_path = case_folder / output_name

            merged_df.to_csv(output_path, index=False)

            print(
                f"[Success] Merged {len(combined_data)} databases "
                f"into {output_name}"
            )
            print(
                f"          Final Matrix Shape: "
                f"{merged_df.shape[0]} trials x {merged_df.shape[1]} features"
            )
            print(f"          Saved to: {output_path}")

        else:
            print(f"[Failed] No files were found for {case_key}. Skipping merge.")

if __name__ == "__main__":
    merge_databases()